import { Gig, Seeker } from './types';

export const INITIAL_GIGS: Gig[] = [
  {
    id: 'gig-1',
    title: 'Live Jazz & Soul Set at The Orbit',
    company: 'The Orbit Jazz Club',
    location: 'Braamfontein, Johannesburg',
    budget: 'R4,500 / night',
    category: 'Live Music',
    date: 'Fri, Oct 24 • 8:00 PM',
    description: 'Looking for a premier jazz ensemble or vocalist for a weekend headline showcase in Johannesburg cultural hub.',
    requirements: ['Professional stage setup', 'Own instruments', 'Repertoire of South African jazz classics'],
    applied: false,
    saved: true,
    urgent: true,
    lat: -26.1929,
    lng: 28.0341,
    avatar: 'OJ'
  },
  {
    id: 'gig-2',
    title: 'Senior Flutter & Go Developer',
    company: 'Silicon Cape Tech',
    location: 'Waterfront, Cape Town',
    budget: 'R95,000 / mo',
    category: 'Tech & Dev',
    date: 'Starts Nov 1',
    description: 'Scaling our fintech ledger backend and mobile banking app for South African enterprise markets.',
    requirements: ['4+ years Flutter & Go', 'Experience with local payment gateways (Ozow/PayFast)', 'Remote hybrid available'],
    applied: false,
    saved: false,
    lat: -33.9036,
    lng: 18.4207,
    avatar: 'SC'
  },
  {
    id: 'gig-3',
    title: 'Brand Identity & Visual Designer',
    company: 'Durban Creative House',
    location: 'Umhlanga, Durban',
    budget: 'R28,000 project fee',
    category: 'Design',
    date: '2-week turnaround',
    description: 'Crafting brand collateral and packaging for a luxury coastal lifestyle and surfing brand based in KwaZulu-Natal.',
    requirements: ['Expert in Illustrator & Figma', 'Strong portfolio', 'Coastal aesthetic sensitivity'],
    applied: false,
    saved: true,
    lat: -29.7289,
    lng: 31.0777,
    avatar: 'DC'
  },
  {
    id: 'gig-4',
    title: 'Festival Stage Sound Engineer',
    company: 'Oppikoppi Productions',
    location: 'Hartbeespoort, North West',
    budget: 'R6,200 / event',
    category: 'Production',
    date: 'Sat, Nov 15 • 12 PM - 12 AM',
    description: 'Main stage FOH sound mixing and line check management for annual outdoor rock & indie festival.',
    requirements: ['Midas / DiGiCo console proficiency', 'Outdoor festival experience', 'High endurance'],
    applied: false,
    saved: false,
    lat: -25.7423,
    lng: 27.8697,
    avatar: 'OP'
  },
  {
    id: 'gig-5',
    title: 'VIP Event Host & MC',
    company: 'Sandton Convention Centre',
    location: 'Sandton, Johannesburg',
    budget: 'R12,000 / day',
    category: 'Events',
    date: 'Nov 20 - Nov 21',
    description: 'Bilingual MC (English & Zulu) required for annual African Tech Summit keynotes and executive awards dinner.',
    requirements: ['Exceptional stage presence', 'Bilingual fluency', 'Formal business wardrobe'],
    applied: false,
    saved: false,
    lat: -26.1076,
    lng: 28.0567,
    avatar: 'SS'
  },
  {
    id: 'gig-6',
    title: 'Botanical Garden Acoustic Session',
    company: 'Kirstenbosch Summer Sunset',
    location: 'Kirstenbosch, Cape Town',
    budget: 'R5,000 / set',
    category: 'Live Music',
    date: 'Sun, Nov 30 • 5:00 PM',
    description: 'Acoustic singer-songwriter performance slot for the world-renowned Kirstenbosch botanical garden sunset concert series.',
    requirements: ['Original or well-curated indie folk repertoire', 'Acoustic rig', 'Professional EPK'],
    applied: false,
    saved: false,
    lat: -33.9875,
    lng: 18.4323,
    avatar: 'KB'
  },
  {
    id: 'gig-7',
    title: 'Eastern Cape Wind Farm UI Engineer',
    company: 'Ubuntu Green Energy',
    location: 'Gqeberha (Port Elizabeth)',
    budget: 'R750 / hr',
    category: 'Tech & Dev',
    date: 'Immediate start',
    description: 'Building telemetry dashboard UI for renewable wind turbine monitoring arrays across Eastern Cape farms.',
    requirements: ['React / TypeScript / Tailwind', 'Data visualization experience', 'IoT websocket integration'],
    applied: false,
    saved: false,
    lat: -33.9608,
    lng: 25.6022,
    avatar: 'UG'
  }
];

export const INITIAL_SEEKERS: Seeker[] = [
  {
    id: 'seek-1',
    name: 'Sipho Khumalo',
    trade: 'Live Sound & FOH Engineer',
    rate: 'R550 / hr',
    location: 'Johannesburg, Gauteng',
    bio: 'Professional FOH & monitor engineer with 8+ years experience mixing live bands, jazz festivals, and arena tours across SA.',
    avatar: 'SK',
    skills: ['Midas Pro', 'DiGiCo SD', 'Acoustic Tuning', 'Dante Certified'],
    hired: false
  },
  {
    id: 'seek-2',
    name: 'Chloe van der Merwe',
    trade: 'Senior React & UI/UX Specialist',
    rate: 'R850 / hr',
    location: 'Cape Town, Western Cape',
    bio: 'Full-stack software engineer specializing in high-performance web applications, Tailwind CSS, and interactive design systems.',
    avatar: 'CM',
    skills: ['React', 'TypeScript', 'Tailwind', 'Next.js', 'Figma'],
    hired: false
  },
  {
    id: 'seek-3',
    name: 'Thabo Mokoena',
    trade: 'Bilingual Event MC & Keynote Host',
    rate: 'R1,200 / hr',
    location: 'Sandton, Gauteng',
    bio: 'Charismatic corporate and festival MC fluent in English, isiZulu, and Sesotho with extensive stage presence.',
    avatar: 'TM',
    skills: ['Public Speaking', 'Bilingual', 'Panel Moderation', 'Live Hosting'],
    hired: false
  },
  {
    id: 'seek-4',
    name: 'Jessica Naidoo',
    trade: 'Brand Identity & Packaging Designer',
    rate: 'R600 / hr',
    location: 'Durban, KwaZulu-Natal',
    bio: 'Creative director crafting premium visual identities and sustainable packaging for African lifestyle and luxury brands.',
    avatar: 'JN',
    skills: ['Adobe Illustrator', 'Brand Strategy', 'Typography', 'Packaging Design'],
    hired: false
  },
  {
    id: 'seek-5',
    name: 'Liam O’Connor',
    trade: 'Session Guitarist & Producer',
    rate: 'R500 / hr',
    location: 'Stellenbosch, Western Cape',
    bio: 'Versatile session guitarist skilled in jazz, afro-soul, indie rock, and blues. Available for studio recording or live sets.',
    avatar: 'LO',
    skills: ['Electric Guitar', 'Logic Pro', 'Session Recording', 'Improvisation'],
    hired: false
  }
];
